version: '2'
services:
  web:
    build: .
    network_mode: host
    ports:
     - "80:3003"
    command: /bin/bash -c "sleep 60 && npm start"
    depends_on:
      - cassandra
    # mem_limit: 512M
  cassandra:
    image: "cassandra:3.11"
    network_mode: host
    environment:
      - "MAX_HEAP_SIZE=512M"
      - "HEAP_NEWSIZE=256M"
      - CASSANDRA_SEEDS=35.166.43.127
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_BROADCAST_ADDRESS=34.210.151.251
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    # mem_limit: 1024M
    # cpu_quota: 50000
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
    restart: always
    volumes:
      - ~/docker_cassandra_data:/var/lib/cassandra
      - ./otherServers/node2/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./otherServers/node2/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
